"""
CyberShield-X — SIEM Alert Engine
Consumes ML inference results from Kafka, deduplicates, assigns severity,
enriches with threat-intel, and persists to TimescaleDB.
"""

from __future__ import annotations

import hashlib
import json
import logging
import time
import uuid
from collections import defaultdict
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone, timedelta
from typing import Any, Dict, List, Optional

logger = logging.getLogger("cybershield.alerting.alert_engine")


# ──────────────────────────────────────────────
# Models
# ──────────────────────────────────────────────

@dataclass
class Alert:
    """Security alert generated by the engine."""

    alert_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    event_ids: List[str] = field(default_factory=list)
    source_ip: Optional[str] = None
    destination_ip: Optional[str] = None
    attack_type: str = "UNKNOWN"
    threat_score: float = 0.0
    severity: str = "LOW"
    mitre_technique: Optional[str] = None
    mitre_tactic: Optional[str] = None
    kill_chain_stage: Optional[str] = None
    whois_info: Optional[Dict[str, Any]] = None
    threat_intel: Optional[Dict[str, Any]] = None
    geo_info: Optional[Dict[str, Any]] = None
    confidence: float = 0.0
    is_suppressed: bool = False
    analyst_feedback: Optional[str] = None  # TP / FP / UNKNOWN
    raw_events: List[Dict[str, Any]] = field(default_factory=list)


# ──────────────────────────────────────────────
# Severity mapper
# ──────────────────────────────────────────────

def assign_severity(threat_score: float) -> str:
    """Map threat score to severity level.

    CRITICAL  >0.95
    HIGH      0.80–0.95
    MEDIUM    0.60–0.80
    LOW       <0.60
    """
    if threat_score > 0.95:
        return "CRITICAL"
    elif threat_score > 0.80:
        return "HIGH"
    elif threat_score > 0.60:
        return "MEDIUM"
    return "LOW"


# ──────────────────────────────────────────────
# Deduplication
# ──────────────────────────────────────────────

class AlertDeduplicator:
    """Dedup alerts: same source + attack type within a time window → single alert.

    Parameters
    ----------
    window_seconds : int
        Deduplication window (default 300 = 5 min).
    """

    def __init__(self, window_seconds: int = 300) -> None:
        self._window = window_seconds
        # key → (first_seen_ts, alert)
        self._cache: Dict[str, tuple[float, Alert]] = {}

    def _key(self, source_ip: str, attack_type: str) -> str:
        return hashlib.sha256(f"{source_ip}:{attack_type}".encode()).hexdigest()[:16]

    def check(self, source_ip: str, attack_type: str, event_id: str) -> Optional[Alert]:
        """Return existing alert if within window, else None.

        If duplicate, the event_id is appended to the existing alert.
        """
        key = self._key(source_ip, attack_type)
        now = time.time()

        if key in self._cache:
            first_ts, existing_alert = self._cache[key]
            if now - first_ts < self._window:
                existing_alert.event_ids.append(event_id)
                return existing_alert
            else:
                del self._cache[key]

        return None

    def register(self, source_ip: str, attack_type: str, alert: Alert) -> None:
        """Register a new alert for deduplication."""
        key = self._key(source_ip, attack_type)
        self._cache[key] = (time.time(), alert)

    def cleanup(self) -> int:
        """Remove expired entries. Returns number removed."""
        now = time.time()
        expired = [k for k, (ts, _) in self._cache.items() if now - ts >= self._window]
        for k in expired:
            del self._cache[k]
        return len(expired)


# ──────────────────────────────────────────────
# Noise suppression (ML-based FP filter)
# ──────────────────────────────────────────────

class FalsePositiveFilter:
    """ML-based false positive filter trained on analyst feedback.

    Uses a simple threshold + feedback history. Can be upgraded to
    a full classifier once enough feedback is collected.
    """

    def __init__(self, threshold: float = 0.3) -> None:
        self._threshold = threshold
        # source_ip → list of (threat_score, is_fp)
        self._feedback: Dict[str, List[tuple[float, bool]]] = defaultdict(list)

    def record_feedback(self, source_ip: str, threat_score: float, is_false_positive: bool) -> None:
        """Record analyst feedback for future suppression learning."""
        self._feedback[source_ip].append((threat_score, is_false_positive))
        logger.debug("Recorded feedback for %s: score=%.2f fp=%s", source_ip, threat_score, is_false_positive)

    def should_suppress(self, source_ip: str, threat_score: float) -> bool:
        """Check if an alert should be suppressed based on FP history.

        Suppressed if: the source IP has >80% false-positive rate for similar score ranges.
        """
        history = self._feedback.get(source_ip, [])
        if len(history) < 3:
            return False  # not enough data

        # Filter to similar score range (±0.1)
        similar = [fp for score, fp in history if abs(score - threat_score) < 0.1]
        if len(similar) < 3:
            return False

        fp_rate = sum(1 for fp in similar if fp) / len(similar)
        return fp_rate > 0.8


# ──────────────────────────────────────────────
# Threat Intel Enricher (stubs for VT, WHOIS, GeoIP)
# ──────────────────────────────────────────────

class ThreatIntelEnricher:
    """Enriches alerts with WHOIS, VirusTotal, and GeoIP data.

    In production, these call external APIs. Here we provide the interface
    with graceful fallbacks.
    """

    def __init__(
        self,
        virustotal_api_key: Optional[str] = None,
    ) -> None:
        self._vt_key = virustotal_api_key

    async def enrich_whois(self, ip: str) -> Dict[str, Any]:
        """Look up WHOIS data for an IP."""
        try:
            import httpx

            async with httpx.AsyncClient(timeout=5) as client:
                resp = await client.get(f"https://whois.arin.net/rest/ip/{ip}", headers={"Accept": "application/json"})
                if resp.status_code == 200:
                    return resp.json()
        except Exception:
            logger.debug("WHOIS lookup failed for %s", ip)
        return {"ip": ip, "status": "unavailable"}

    async def enrich_virustotal(self, ip: str) -> Dict[str, Any]:
        """Query VirusTotal for IP reputation."""
        if not self._vt_key:
            return {"ip": ip, "status": "no_api_key"}
        try:
            import httpx

            async with httpx.AsyncClient(timeout=10) as client:
                resp = await client.get(
                    f"https://www.virustotal.com/api/v3/ip_addresses/{ip}",
                    headers={"x-apikey": self._vt_key},
                )
                if resp.status_code == 200:
                    data = resp.json().get("data", {}).get("attributes", {})
                    return {
                        "ip": ip,
                        "reputation": data.get("reputation", 0),
                        "malicious": data.get("last_analysis_stats", {}).get("malicious", 0),
                        "suspicious": data.get("last_analysis_stats", {}).get("suspicious", 0),
                    }
        except Exception:
            logger.debug("VirusTotal lookup failed for %s", ip)
        return {"ip": ip, "status": "unavailable"}

    async def enrich(self, ip: str) -> Dict[str, Dict[str, Any]]:
        """Run all enrichments for an IP."""
        import asyncio

        whois_task = self.enrich_whois(ip)
        vt_task = self.enrich_virustotal(ip)
        whois_data, vt_data = await asyncio.gather(whois_task, vt_task)
        return {"whois": whois_data, "virustotal": vt_data}


# ──────────────────────────────────────────────
# Alert Engine
# ──────────────────────────────────────────────

class AlertEngine:
    """Core alert engine that processes ML results into actionable alerts.

    Parameters
    ----------
    kafka_producer : object
        For publishing alerts to ``security-alerts`` topic.
    db_client : object, optional
        TimescaleDB client for alert persistence.
    enricher : ThreatIntelEnricher, optional
        Threat intel enricher.
    """

    def __init__(
        self,
        kafka_producer: Any = None,
        db_client: Any = None,
        enricher: Optional[ThreatIntelEnricher] = None,
    ) -> None:
        self._producer = kafka_producer
        self._db = db_client
        self._enricher = enricher or ThreatIntelEnricher()
        self._dedup = AlertDeduplicator(window_seconds=300)
        self._fp_filter = FalsePositiveFilter()
        self._alert_count = 0

    async def process_inference_result(self, result: Dict[str, Any]) -> Optional[Alert]:
        """Process a single ML inference result and generate an alert if warranted.

        Parameters
        ----------
        result : dict
            Must contain: event_id, threat_score, attack_type, source_ip.
            Optional: confidence, mitre_technique, features.

        Returns
        -------
        Alert or None if deduplicated/suppressed.
        """
        event_id = result.get("event_id", str(uuid.uuid4()))
        source_ip = result.get("source_ip", "unknown")
        attack_type = result.get("attack_type", "UNKNOWN")
        threat_score = result.get("threat_score", 0.0)
        confidence = result.get("confidence", 0.0)

        # ── Noise suppression ──
        if self._fp_filter.should_suppress(source_ip, threat_score):
            logger.debug("Suppressed alert for %s (FP filter)", source_ip)
            return None

        # ── Deduplication ──
        existing = self._dedup.check(source_ip, attack_type, event_id)
        if existing:
            logger.debug("Dedup: merged event %s into alert %s", event_id, existing.alert_id)
            return None

        # ── Build alert ──
        alert = Alert(
            event_ids=[event_id],
            source_ip=source_ip,
            destination_ip=result.get("destination_ip"),
            attack_type=attack_type,
            threat_score=threat_score,
            severity=assign_severity(threat_score),
            mitre_technique=result.get("mitre_technique"),
            confidence=confidence,
        )

        # ── Enrich ──
        if source_ip and source_ip != "unknown":
            try:
                intel = await self._enricher.enrich(source_ip)
                alert.whois_info = intel.get("whois")
                alert.threat_intel = intel.get("virustotal")
            except Exception:
                logger.debug("Enrichment failed for %s", source_ip, exc_info=True)

        # ── Register for dedup ──
        self._dedup.register(source_ip, attack_type, alert)

        # ── Persist to TimescaleDB ──
        if self._db:
            try:
                await self._persist_alert(alert)
            except Exception:
                logger.error("Failed to persist alert %s", alert.alert_id, exc_info=True)

        # ── Publish to Kafka ──
        if self._producer:
            try:
                self._producer.produce("security-alerts", asdict(alert))
            except Exception:
                logger.error("Failed to publish alert %s", alert.alert_id, exc_info=True)

        self._alert_count += 1
        logger.info(
            "Alert %s | %s | %s | score=%.3f | %s",
            alert.alert_id[:8], alert.severity, attack_type, threat_score, source_ip,
        )
        return alert

    async def _persist_alert(self, alert: Alert) -> None:
        """Insert alert into TimescaleDB."""
        query = """
            INSERT INTO security_alerts
                (alert_id, timestamp, source_ip, destination_ip, attack_type,
                 threat_score, severity, mitre_technique, confidence, event_ids)
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
        """
        await self._db.execute(
            query,
            alert.alert_id,
            alert.timestamp,
            alert.source_ip,
            alert.destination_ip,
            alert.attack_type,
            alert.threat_score,
            alert.severity,
            alert.mitre_technique,
            alert.confidence,
            json.dumps(alert.event_ids),
        )

    def record_analyst_feedback(
        self, alert_id: str, source_ip: str, threat_score: float, is_fp: bool
    ) -> None:
        """Record analyst TP/FP feedback for the FP filter."""
        self._fp_filter.record_feedback(source_ip, threat_score, is_fp)

    @property
    def alert_count(self) -> int:
        return self._alert_count
